version: '3.8'

services:

  db:
    container_name: shop-database
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - shop_pg_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    container_name: backend
    build: .
    restart: always
    environment:
      DB_HOST: db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '80:80'
    command: python manage.py runserver 0.0.0.0:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seller/:/opt/seller




volumes:
  shop_pg_data:
    driver: local
