# Generated by Django 4.1.7 on 2023-03-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Уровень в иерархии'),
        ),
        migrations.AddField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(related_name='seller', to='seller.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='building',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='debt',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Задолженность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='seller.seller', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')], default=1, verbose_name='Тип продавца'),
        ),
    ]
