# Generated by Django 4.1.7 on 2023-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AddField(
            model_name='seller',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
