# Generated by Django 4.1.7 on 2023-03-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_options_remove_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.seller', verbose_name='Поставщик'),
        ),
    ]
